export const en = {
  nav: { manifesto: "[MANIFESTO]", products: "[PRODUCTS]", login: "[LOGIN]", blog: "[BLOG]", dashboard: "[DASHBOARD]" },
  hero: {
    status: "System Status: Operational",
    title_line1: "Rewrite",
    title_line2: "The Source Code",
    description: "The modern world is designed to keep you weak, distracted, and dependent. We provide the digital weaponry to disconnect from the noise and rebuild your biology and psychology.",
    cta_primary: "Initialize Protocol",
    cta_secondary: "View Catalog",
  },
  cards: {
    body: { title: "The Body", desc: "Physical sovereignty. Learn to manipulate the hardware.", link: "Access Data >>" },
    mind: { title: "The Mind", desc: "Dopamine control and focus architecture.", link: "Access Data >>" },
    code: { title: "The Code", desc: "Financial independence through digital leverage.", link: "Access Data >>" },
  },
  featured: {
    label: "[LATEST_DROP]",
    title: "Unconnected Society",
    link: "// View All Archives",
    badge: "NEW ARRIVAL",
    product_title: "The Blueprint",
    product_desc: "The complete manual for disconnecting from the matrix. Includes nutrition protocols, mental models, and financial strategies.",
    features: ["200+ Pages of Tactics", "Audio Companion", "Lifetime Updates"],
    cta: "Secure Access",
    price: "$97",
  },
  blog: {
    title: "Knowledge Base",
    noPosts: "No articles available yet. Check back soon.",
    readMore: "Read more",
    backToBlog: "Back to Blog",
    relatedArticles: "Related Articles",
    minuteRead: "min read",
    publishedOn: "Published on",
    by: "By",
  },
  dashboard: {
    title: "My Dashboard",
    nav: {
      overview: "Overview",
      profile: "My Profile",
      orders: "Order History",
      downloads: "My Downloads",
      logout: "Logout",
    },
    myPurchases: "My Purchases",
    myLibrary: "My Library",
    noPurchases: "No purchases yet. Browse our products to get started.",
    downloadButton: "Download",
    purchaseDate: "Purchased on",
    orderNumber: "Order #",
    viewProducts: "View Products",
  },
  footer: { rights: "© 2025 ALL RIGHTS RESERVED.", location: "[SECURE CONNECTION]", price: "$97" }
}
